name: Deploy to server

on:
    workflow_call:


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            
              
            - name: SSH to Prod server
              uses: appleboy/ssh-action@v1.0.3
              with:
               host: '13.239.29.148'
               username: ${{ secrets.SSH_USER }}
               key: ${{ secrets.SSH_PRIVATE_KEY }}
               script: |
                   echo "Starting Deployment"
                   mkdir devops && cd devops
                   
