name: Deploy to server

on:
    workflow_call:


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            
            
            - name: Debug user
              run: echo "User = ${{ secrets.EC2_SSH_USER }}" && echo "Key = ${{ secrets.EC2_SSH_PRIVATE_KEY }}"
            
            - name: SSH to Prod server
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: '13.239.29.148'
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                script: |
                   mkdir devops && cd devops 
                   echo "welcome to prod-server"
               
                   
