name: Deploy to server

on:
    workflow_call:


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            
              
            - name: SSH to Prod server
              uses: appleboy/ssh-action@v1.0.3
              with:
               host: $${{secrets.SSH_HOST}}
               username: ${{ secrets.USER }}
               script: ${{secrets.SSH_PRIVATE_KEY}}|
                   echo "Starting Deployment"
                   mkdir devops && cd devops
                   
