name: Devsecops end to end pipeline

on: 
    push:
        branches: [main]    


jobs:

    Code-quality:
       uses: ./.github/workflows/code-quality.yml
    
    secrets-scan:
       uses: ./.github/workflows/secrets-scan.yml
       secrets: inherit

    dependency-scan:
       uses: ./.github/workflows/dependency-scan.yml
    
    docker-scan:
       uses: ./.github/workflows/Docker-lint.yml
    
    build:
       needs: [Code-quality,secrets-scan,dependency-scan,docker-scan]
       uses: ./.github/workflows/docker-build-push.yml
       secrets: inherit
    
    trivy-image:
      needs: [build]
      uses: ./.github/workflows/image-scan.yml
      secrets: inherit
    #deploying the app to the server
    deploy:
      needs: [trivy-image]
      uses: ./.github/workflows/Deploy-to-server.yml
      secrets: inherit
      