#build and push will create a docker- image .Hence we need to scan the image scanning for cve's

name: Docker Image scanner

on:
    workflow_call:

jobs:
    image-scanner:
        runs-on: ubuntu-latest

        steps:
             - name: Login into docker hub
               uses: docker/login-action@v3
               with:
                  username: ${{ vars.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }} 
            
             - name: Trivy scanner
               uses: aquasecurity/trivy-action@0.35.0
               with:
                 image-ref: ${{ vars.DOCKERHUB_USER }}/github-actions-practice:${{ github.sha }}
                 severity: 'CRITICAL'
                 exit-code: 1
