# This workflow will scan the codebase for any secrets or sensitive information such as api keys
# passwords,tokens etc. It uses the trufflehog action to perform the scan and will run on every push to the main branch. If any secrets are found, the workflow will fail and provide details about the findings in the logs.
# It will use git leaks for flagging this information
name: secrets-scan

on:
   workflow_call:

jobs:
    secret-scan:
        runs-on: ubuntu:latest
    steps:
        - name: checkout code
          uses: actions/checkout@v4
        #the below actions makes sure that all the versions of the code previously created is also verified
          with:
            fetch-depth: 0

        - name: Run gitleak scanner
          uses: gitleaks/gitleaks-action@v2
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #github actions will create a secrect token and pass that token to the pipeline to check any vulnerabilties

